todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls", namespace="users")),
    path('', include("web.urls", namespace="web")),
]

users/urls.py
from django.urls import path
from users import views


app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("create-task/", views.create_task, name="create_task"),
    path("delete-task/<int:id>/", views.delete_task, name="delete_task"),
    path("edit-task/<int:id>/", views.edit_task, name="edit_task"),
    path("completed-task/<int:id>/", views.completed_task, name="completed_task"),

]

web/urls.py
from web import views
from django.urls import path


app_name = "web"


urlpatterns = [
    path('', views.index, name="index"),
]

main/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=255)
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
import uuid



class create(models.Model):
    student_division= models.CharField(max_length=255)
    student_class = models.CharField(max_length=255)

    def __str__(self):
        return self.student_class


class ToDo(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)/
    username = models.ForeignKey("auth.User",on_delete=models.CASCADE)
    is_deleted = models.BooleanField(default=False)
    creat_task = models.CharField(null=False, blank=False, max_length=120)
    completed_task =models.BooleanField(default=False)


    class Meta:
        verbose_name = 'ToDo'
        verbose_name_plural = 'ToDos'

    def __str__(self):
        return self.creat_task

web/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import ToDo


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "username", "password"]

class ToDoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ['creat_task',]

        widgets = {
            'creat_task': forms.TextInput(attrs={'class': ' task'})
        
        }

main/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
import json

from django.shortcuts import render, reverse, get_object_or_404
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.models import User
from posts.models import Author
from users.models import ToDo
from users.forms import ToDoForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect




from users.forms import UserForm
from main.functions import generate_form_errors

# Create your views here.


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)

                return HttpResponseRedirect("/")

        context = {
            "title": "Login",
            "error": True,
            "message": "Invalid username or password"
        }
        return render(request, "users/login.html", context)
    else:
        context = {
            "title": "Login",

        }
        return render(request, "users/login.html", context)


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse("web:index"))


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)

            user= User.objects.create_user(
                    first_name=instance.first_name,
                    last_name=instance.last_name,
                    email=instance.email,
                    password=instance.password,
                    username=instance.username
                )
            Author.objects.create(
                    name=instance.first_name,
                    user=user
                )

            user = authenticate(
                request, username=instance.username, password=instance.password)
            auth_login(request, user)

            return HttpResponseRedirect(reverse('web:index'))
        else:
            message = generate_form_errors(form)
            form = UserForm()
            context = {
                "title": "Signup",
                "error": True,
                "form": form,
                "message": message
            }
            return render(request, "users/create.html", context)
    else:
        form = UserForm()
        context = {
            'title': "Signup",
            "form": form,
        }
        return render(request, "users/create.html", context=context)


@login_required
def create_task(request):
    if request.method == 'POST':
        form = ToDoForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.username = request.user
            instance.save()

            return HttpResponseRedirect(reverse('web:index'))
    else:
         form = ToDoForm()
         instances = ToDo.objects.filter(is_deleted=False)    
         context = {
                "title" : "Home Page",
                "instances": instances,
                "message" : generate_form_errors(form),
                "form":form
            }
         return render(request, 'users/web/index.html', context=context)
            
        

        
@login_required
def view_task(request):
    instance = ToDo.objects.filter(is_deleted=False)

    context = {
        "instance": instance
    }

    return render(request, "website/event/view_event.html", context)


@login_required
def delete_task(request, id):
    enquiry = get_object_or_404(ToDo, id=id)
    enquiry. is_deleted=True
    enquiry.delete()
    context={}
    # return render(request, "users/web/index.html", context=context)
    return HttpResponseRedirect(reverse('web:index'))



@login_required
def edit_task(request, id):
     instance = get_object_or_404(ToDo, id=id)
     if request.method == 'POST':
        form = ToDoForm(request.POST, instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()

     else:
        form = ToDoForm(instance=instance)
        context={
            "form":form
        }
        return render(request, "users/web/index.html", context=context)


def completed_task(request,id ):
     enquiry = get_object_or_404(ToDo, id=id)
     enquiry.completed_task=True
     enquiry.save()
     return HttpResponseRedirect(reverse('web:index'))

web/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from users.forms import ToDoForm
from users.models import ToDo


def index(request):
    instances = ToDo.objects.filter(is_deleted=False,completed_task=False)
    form = ToDoForm()    
    context = {
        "title" : "Home Page",
        "instances": instances,
         "form": form,  
    }
    return render(request,'users/web/index.html',context=context)

templates/users/auth_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/auth-style.css' %}" />
    <title>{{title}}</title>
  </head>
  <body>
    <section id="login">{% block content %} {% endblock %}</section>
  </body>
</html>

templates/users/create.html
{% extends 'users/auth_base.html' %}
{% load static %}
{% block content %}


    <section class="form">
        <h1>Login page</h1>
        <form action="" method="post">
            {% csrf_token %}
                {% for field in form %}
                    <div class="formrow">
                        <label for="{{field.id_for_label}}">{{field.label}}</label>
                        {{field}}
                    </div>
            {% endfor %}
            <div class="submit">
                {%if error %}
                    <p class="error">{{message}}</p>
                {% endif %}
                <button type="submit">Create a Account</button>
            </div>
            <a href="{% url 'users:login' %}">Login</a>
        </form>
    </section>


{% endblock %}

templates/users/login.html
{% extends 'users/auth_base.html' %} {% load static %}{% block content %}
<section class="form">
  <h1>Login page</h1>
  <form action="" method="post">
    {% csrf_token %}
    <div class="formrow">
      <label for="">USERNAME:</label>
      <input type="text" name="username" id="" />
    </div>
    <div class="formrow">
      <label for="">PASSWORD:</label>
      <input type="password" name="password" id="" />
    </div>
    <div class="submit">
      {%if error %}
      <p class="error">{{message}}</p>
      {% endif %}
      <button type="submit">Login</button>
    </div>
    <a href="{% url 'users:signup' %}">Create a Account</a>
  </form>
</section>
{% endblock %}

templates/users/web/index.html
<!DOCTYPE html>
<html lang="en">

<head>
	{% load static %}
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="" href="{% static './css/main.css' %}">

	<title>Student List 2023</title>
</head>

<body>
	<section class="header">
		<h1 class="left">
			<a href="">
				<img src="{% static 'images/images.jpeg' %}" alt="">
			</a>
		</h1>
		<div class="right">
			{% if request.user.is_authenticated%}
			<span>{{request.user.first_name}} {{request.user.last_name}}</span>
			<a href="{% url 'users:logout' %}">Logout</a>
			{% else %}
			<a href="{% url 'users:login' %}">Login</a>
			{% endif %}
		</div>
	</section>

	<header>
		<h1>Student List 2021</h1>

		<form id="new-task-form" method="post" action="{% url 'users:create_task' %}">
			{% csrf_token %}
			<label class="wes" for="{{form.creat_task.id_for_label}}">Create task</label>
			{{form.creat_task}}

			<input  type="submit" id="new-task-submit" value="Add task" />
		</form>
	</header>
	<main>
		<section class="task-list">
			<h2>Tasks</h2>
			{% if instances %}
			<div id="tasks">
				{% for instance in instances %}
				<div class="task">
					<div class="content">
						<input type="text" class="text" value="{{instance.creat_task}}" readonly>
					</div>
					<div class="actions">
						<a href="{% url 'users:edit_task' id=instance.id %}">
							<button class="edit">Edit</button></a>
						<a href="{% url 'users:delete_task' id=instance.id  %}"><button
								class="delete">Delete</button></a>
						<a href="{% url 'users:completed_task' id=instance.id  %}"><button
								class="delete ">Completed</button></a>
					</div>
				</div>
				{% endfor %}
			</div>
			{% endif %}
		</section>
	</main>
	<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</body>

</html>